- name: dpkg-reconfigure tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
- name: dpkg-reconfigure console-setup
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive console-setup
